#!/usr/bin/env sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

DESTINATION=${1}
if [ -z "${DESTINATION}" ]; then
  >&2 echo "usage: $0 <path/to/destination>"
  exit 1
fi

REQUEST=$(cat <&0)
FEED=$(echo "${REQUEST}" | jq -r '.source.feed' | tr '[:upper:]' '[:lower:]')
URL="https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-${FEED}.meta"

CONTENT=$(curl --silent -L ${URL} | tr -dc '[:print:]\n' | grep 'sha256:')

SHA=${CONTENT:7}

jq -n '
{
  "sha256": "${SHA}"
}
' > "${DESTINATION}/${FEED}.sha256"
